"use client";

import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { UploadButton } from "~/app/utils/uploadthing";
import {useRouter} from "next/navigation";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const Navbar = () => {

    const router = useRouter();

    return (
        <nav className="bg-gray-800 text-white">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-16">
                    {/* Logo/Brand */}
                    <div className="flex-shrink-0">
                        <Link href="/click_to_punch_nlp/public" className="text-xl font-bold">
                            JHU Course Vote
                        </Link>
                    </div>

                    {/* Navigation Links */}
                    <div className="flex space-x-4">
                        <Link href="/" className="px-3 py-2 rounded-md hover:bg-gray-700 transition-colors">
                            Home
                        </Link>
                        <Link href="/about" className="px-3 py-2 rounded-md hover:bg-gray-700 transition-colors">
                            About us
                        </Link>

                        <div className="flex flex-row">
                            <SignedOut>
                                <SignInButton />
                            </SignedOut>
                            <SignedIn>
                                <UserButton />
                            </SignedIn>
                        </div>


                    </div>
                </div>
            </div>
        </nav>
    );
};
